/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("minminsweeper.kotlin-application-conventions")
    id("org.jetbrains.compose") version "1.3.1"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(compose.desktop.currentOs)
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("minminsweeper.app.AppKt")
}

compose.desktop {
    application {
        mainClass = "AppKt"
    }
}